# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Sat Feb 14 22:18:14 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from pyqtgraph.parametertree import ParameterTree

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(726, 576)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(726, 576))
        MainWindow.setMaximumSize(QtCore.QSize(726, 576))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 721, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_current = QtGui.QWidget()
        self.tab_current.setObjectName(_fromUtf8("tab_current"))
        self.button_start = QtGui.QPushButton(self.tab_current)
        self.button_start.setGeometry(QtCore.QRect(10, 450, 96, 33))
        self.button_start.setObjectName(_fromUtf8("button_start"))
        self.checkBox_plotShowing = QtGui.QCheckBox(self.tab_current)
        self.checkBox_plotShowing.setGeometry(QtCore.QRect(300, 440, 121, 41))
        self.checkBox_plotShowing.setChecked(True)
        self.checkBox_plotShowing.setObjectName(_fromUtf8("checkBox_plotShowing"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_current)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 711, 441))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphicsView = ParameterTree(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.table_axes = QtGui.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_axes.sizePolicy().hasHeightForWidth())
        self.table_axes.setSizePolicy(sizePolicy)
        self.table_axes.setMaximumSize(QtCore.QSize(364, 16777215))
        self.table_axes.setFrameShape(QtGui.QFrame.Box)
        self.table_axes.setFrameShadow(QtGui.QFrame.Sunken)
        self.table_axes.setLineWidth(0)
        self.table_axes.setShowGrid(True)
        self.table_axes.setCornerButtonEnabled(True)
        self.table_axes.setRowCount(4)
        self.table_axes.setColumnCount(4)
        self.table_axes.setObjectName(_fromUtf8("table_axes"))
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(3, item)
        self.table_axes.horizontalHeader().setCascadingSectionResizes(False)
        self.table_axes.horizontalHeader().setDefaultSectionSize(82)
        self.table_axes.verticalHeader().setMinimumSectionSize(40)
        self.table_axes.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.table_axes)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.sample_size_slider = QtGui.QSlider(self.horizontalLayoutWidget)
        self.sample_size_slider.setMinimum(1)
        self.sample_size_slider.setMaximum(10)
        self.sample_size_slider.setProperty("value", 5)
        self.sample_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sample_size_slider.setObjectName(_fromUtf8("sample_size_slider"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sample_size_slider)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.show_grid_checkbox = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.show_grid_checkbox.setText(_fromUtf8(""))
        self.show_grid_checkbox.setChecked(True)
        self.show_grid_checkbox.setObjectName(_fromUtf8("show_grid_checkbox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.show_grid_checkbox)
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.checkbox_translucent = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkbox_translucent.setText(_fromUtf8(""))
        self.checkbox_translucent.setChecked(True)
        self.checkbox_translucent.setObjectName(_fromUtf8("checkbox_translucent"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkbox_translucent)
        self.button_Reset_plots = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.button_Reset_plots.setObjectName(_fromUtf8("button_Reset_plots"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.button_Reset_plots)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.checkBox_logging = QtGui.QCheckBox(self.tab_current)
        self.checkBox_logging.setGeometry(QtCore.QRect(560, 450, 61, 26))
        self.checkBox_logging.setChecked(False)
        self.checkBox_logging.setObjectName(_fromUtf8("checkBox_logging"))
        self.progressBar = QtGui.QProgressBar(self.tab_current)
        self.progressBar.setGeometry(QtCore.QRect(150, 450, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.evolutions_label = QtGui.QLabel(self.tab_current)
        self.evolutions_label.setGeometry(QtCore.QRect(170, 470, 81, 21))
        self.evolutions_label.setObjectName(_fromUtf8("evolutions_label"))
        self.checkbox_graphs = QtGui.QCheckBox(self.tab_current)
        self.checkbox_graphs.setGeometry(QtCore.QRect(430, 450, 121, 26))
        self.checkbox_graphs.setChecked(True)
        self.checkbox_graphs.setObjectName(_fromUtf8("checkbox_graphs"))
        self.tabWidget.addTab(self.tab_current, _fromUtf8(""))
        self.tab_stats = QtGui.QWidget()
        self.tab_stats.setObjectName(_fromUtf8("tab_stats"))
        self.label_2 = QtGui.QLabel(self.tab_stats)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 131, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.datasetComboBox = QtGui.QComboBox(self.tab_stats)
        self.datasetComboBox.setGeometry(QtCore.QRect(160, 10, 191, 29))
        self.datasetComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.datasetComboBox.setObjectName(_fromUtf8("datasetComboBox"))
        self.datasetComboBox.addItem(_fromUtf8(""))
        self.table_results = QtGui.QTableWidget(self.tab_stats)
        self.table_results.setGeometry(QtCore.QRect(10, 90, 701, 381))
        self.table_results.setObjectName(_fromUtf8("table_results"))
        self.table_results.setColumnCount(6)
        self.table_results.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_results.setHorizontalHeaderItem(5, item)
        self.label_resgroup_details = QtGui.QLabel(self.tab_stats)
        self.label_resgroup_details.setGeometry(QtCore.QRect(380, 10, 321, 21))
        self.label_resgroup_details.setText(_fromUtf8(""))
        self.label_resgroup_details.setObjectName(_fromUtf8("label_resgroup_details"))
        self.label_5 = QtGui.QLabel(self.tab_stats)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 65, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_dataset = QtGui.QLabel(self.tab_stats)
        self.label_dataset.setGeometry(QtCore.QRect(80, 50, 91, 21))
        self.label_dataset.setText(_fromUtf8(""))
        self.label_dataset.setObjectName(_fromUtf8("label_dataset"))
        self.label_6 = QtGui.QLabel(self.tab_stats)
        self.label_6.setGeometry(QtCore.QRect(180, 50, 65, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_classes = QtGui.QLabel(self.tab_stats)
        self.label_classes.setGeometry(QtCore.QRect(240, 50, 31, 21))
        self.label_classes.setText(_fromUtf8(""))
        self.label_classes.setObjectName(_fromUtf8("label_classes"))
        self.label_7 = QtGui.QLabel(self.tab_stats)
        self.label_7.setGeometry(QtCore.QRect(290, 50, 121, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_distribution = QtGui.QLabel(self.tab_stats)
        self.label_distribution.setGeometry(QtCore.QRect(410, 50, 301, 21))
        self.label_distribution.setText(_fromUtf8(""))
        self.label_distribution.setObjectName(_fromUtf8("label_distribution"))
        self.tabWidget.addTab(self.tab_stats, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Evolutional clustering", None))
        self.button_start.setText(_translate("MainWindow", "Start", None))
        self.checkBox_plotShowing.setText(_translate("MainWindow", "Show 3D plot", None))
        self.label.setText(_translate("MainWindow", "3D Plot settings", None))
        item = self.table_axes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Axes", None))
        item = self.table_axes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Visible", None))
        item = self.table_axes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Centroids", None))
        item = self.table_axes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Result", None))
        self.label_3.setText(_translate("MainWindow", "Sample size", None))
        self.label_4.setText(_translate("MainWindow", "Show grid", None))
        self.label_8.setText(_translate("MainWindow", "Translucent", None))
        self.button_Reset_plots.setText(_translate("MainWindow", "Reset plots", None))
        self.checkBox_logging.setText(_translate("MainWindow", "Log", None))
        self.evolutions_label.setText(_translate("MainWindow", "(0 of 100)", None))
        self.checkbox_graphs.setText(_translate("MainWindow", "Show graphs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_current), _translate("MainWindow", "Current Run", None))
        self.label_2.setText(_translate("MainWindow", "Select result group", None))
        self.datasetComboBox.setItemText(0, _translate("MainWindow", "---", None))
        self.table_results.setSortingEnabled(True)
        item = self.table_results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.table_results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DCls", None))
        item.setToolTip(_translate("MainWindow", "Detected classes", None))
        item = self.table_results.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DDist", None))
        item.setToolTip(_translate("MainWindow", "<html><head/><body><p>Detected distribution of classes</p></body></html>", None))
        item = self.table_results.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Oindex", None))
        item = self.table_results.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Dindex", None))
        item.setToolTip(_translate("MainWindow", "Best detected fitness", None))
        item = self.table_results.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Details", None))
        item.setToolTip(_translate("MainWindow", "Show graphs", None))
        self.label_5.setText(_translate("MainWindow", "Dataset: ", None))
        self.label_6.setText(_translate("MainWindow", "Classes:", None))
        self.label_7.setText(_translate("MainWindow", "Class distribution:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stats), _translate("MainWindow", "Stats", None))
