# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Thu Feb  5 22:54:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from pyqtgraph.parametertree import ParameterTree

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(726, 576)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 721, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_current = QtGui.QWidget()
        self.tab_current.setObjectName(_fromUtf8("tab_current"))
        self.button_start = QtGui.QPushButton(self.tab_current)
        self.button_start.setGeometry(QtCore.QRect(10, 450, 96, 33))
        self.button_start.setObjectName(_fromUtf8("button_start"))
        self.checkBox_plotShowing = QtGui.QCheckBox(self.tab_current)
        self.checkBox_plotShowing.setGeometry(QtCore.QRect(300, 440, 121, 41))
        self.checkBox_plotShowing.setChecked(True)
        self.checkBox_plotShowing.setObjectName(_fromUtf8("checkBox_plotShowing"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_current)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 711, 441))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphicsView = ParameterTree(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.table_axes = QtGui.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_axes.sizePolicy().hasHeightForWidth())
        self.table_axes.setSizePolicy(sizePolicy)
        self.table_axes.setMaximumSize(QtCore.QSize(364, 16777215))
        self.table_axes.setFrameShape(QtGui.QFrame.Box)
        self.table_axes.setFrameShadow(QtGui.QFrame.Sunken)
        self.table_axes.setLineWidth(0)
        self.table_axes.setShowGrid(True)
        self.table_axes.setCornerButtonEnabled(True)
        self.table_axes.setRowCount(4)
        self.table_axes.setColumnCount(4)
        self.table_axes.setObjectName(_fromUtf8("table_axes"))
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_axes.setHorizontalHeaderItem(3, item)
        self.table_axes.horizontalHeader().setCascadingSectionResizes(False)
        self.table_axes.horizontalHeader().setDefaultSectionSize(82)
        self.table_axes.verticalHeader().setMinimumSectionSize(40)
        self.table_axes.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.table_axes)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.sample_size_slider = QtGui.QSlider(self.horizontalLayoutWidget)
        self.sample_size_slider.setMinimum(1)
        self.sample_size_slider.setMaximum(10)
        self.sample_size_slider.setProperty("value", 5)
        self.sample_size_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sample_size_slider.setObjectName(_fromUtf8("sample_size_slider"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sample_size_slider)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.show_grid_checkbox = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.show_grid_checkbox.setText(_fromUtf8(""))
        self.show_grid_checkbox.setChecked(True)
        self.show_grid_checkbox.setObjectName(_fromUtf8("show_grid_checkbox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.show_grid_checkbox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.checkBox_logging = QtGui.QCheckBox(self.tab_current)
        self.checkBox_logging.setGeometry(QtCore.QRect(560, 450, 61, 26))
        self.checkBox_logging.setChecked(False)
        self.checkBox_logging.setObjectName(_fromUtf8("checkBox_logging"))
        self.progressBar = QtGui.QProgressBar(self.tab_current)
        self.progressBar.setGeometry(QtCore.QRect(150, 450, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.evolutions_label = QtGui.QLabel(self.tab_current)
        self.evolutions_label.setGeometry(QtCore.QRect(170, 470, 81, 21))
        self.evolutions_label.setObjectName(_fromUtf8("evolutions_label"))
        self.checkbox_graphs = QtGui.QCheckBox(self.tab_current)
        self.checkbox_graphs.setGeometry(QtCore.QRect(430, 450, 121, 26))
        self.checkbox_graphs.setChecked(True)
        self.checkbox_graphs.setObjectName(_fromUtf8("checkbox_graphs"))
        self.tabWidget.addTab(self.tab_current, _fromUtf8(""))
        self.tab_stats = QtGui.QWidget()
        self.tab_stats.setObjectName(_fromUtf8("tab_stats"))
        self.tabWidget.addTab(self.tab_stats, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Evolutional clustering", None))
        self.button_start.setText(_translate("MainWindow", "Start", None))
        self.checkBox_plotShowing.setText(_translate("MainWindow", "Show 3D plot", None))
        self.label.setText(_translate("MainWindow", "3D Plot settings", None))
        item = self.table_axes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Axes", None))
        item = self.table_axes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Visible", None))
        item = self.table_axes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Centroids", None))
        item = self.table_axes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Result", None))
        self.label_3.setText(_translate("MainWindow", "Sample size", None))
        self.label_4.setText(_translate("MainWindow", "Show grid", None))
        self.checkBox_logging.setText(_translate("MainWindow", "Log", None))
        self.evolutions_label.setText(_translate("MainWindow", "(0 of 100)", None))
        self.checkbox_graphs.setText(_translate("MainWindow", "Show graphs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_current), _translate("MainWindow", "Current Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stats), _translate("MainWindow", "Stats", None))
